#!/bin/bash
# -------------------------------------------------------------------------- #
# Copyright 2013, Gareth Bult <gareth@linux.co.uk>                           #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #
ROOT=$(dirname $(dirname $(dirname $0)))
source ${ROOT}/hooks/vdc/common.sh
tool="${ROOT}/hooks/vdc/tool.py"

vdc_log "Running CPDS with ($1) ($2) ($3) ($4)"

SRC=$1
DST=$2
VMID=$3
DSID=$4

DISK_ID=$(echo $SRC|awk -F. '{print $NF}')

XPATH="/var/lib/one/remotes/datastore/xpath.rb -s"
unset i j XPATH_ELEMENTS
while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <(onevm show -x $VMID|$XPATH \
            /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/IMAGE_ID \
            /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/DATASTORE \
            /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/SOURCE )


IMAGE_ID="${XPATH_ELEMENTS[j++]}"
HOST="${XPATH_ELEMENTS[j++]}"

NAME="ON_${IMAGE_ID}_${VMID}"
eval `${tool} getpath ${NAME}`

if [ -z "${IM_PATH}" ] ; then
    vdc_log "Using static path for source"
    IM_PATH="${XPATH_ELEMENTS[j++]}"
else
    vdc_log "Using non-persistent path for source"
fi

vdc_log "ssh_make_path ${HOST} ${DST}"
ssh_make_path ${HOST} ${DST}
execute ${HOST} "sudo cp -ra ${IM_PATH}/* ${DST}/"
exit 0




#conf="${ROOT}/hooks/vdc/mkconfig.py"
#gids="${ROOT}/hooks/vdc/get_image_ids.py"
#gpaths="${ROOT}/hooks/vdc/get_image_path.py"
#vdc="${ROOT}/../vdc-nebula/remotes/binaries"

#vdc_log "${gpaths} $VMID"
#eval `${gpaths} $VMID $DISK_ID`
#eval `${tool} ln $VMID $DSID $DST_HOST`
#vdc_log "ssh_make_path $DS_NAME $DST"
#ssh_make_path $DS_NAME $DST
#execute $DS_NAME "sudo cp -ra $IM_PATH/* $DST/"
#exit 0
