#!/bin/bash
# -------------------------------------------------------------------------- #
# Copyright 2013, Gareth Bult <gareth@linux.co.uk>                           #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #
vdc=/var/lib/one/vdc-nebula/remotes/binaries

deploy_id=$1
dest_host=$2

function vdc_log
{
   logger -t vdc-nebula "$1"
}

vdc_log "Migration failure with VMID=${deploy_id} HOST=${dest_host}"

function execute
{
    vdc_log "* exec @$1 $2"
    SSH_EXEC_ERR=`ssh $1 sh -s 2>&1 1>/dev/null <<EOF
export LANG=C
export LC_ALL=C
$2
EOF`
    SSH_EXEC_RC=$?
    if [ $SSH_EXEC_RC -ne 0 ]; then
        vdc_log "Command \"$2\" failed: $SSH_EXEC_ERR"

        if [ -n "$3" ]; then
            vdc_log "$3"
        else
            vdc_log "Error executing $2: $SSH_EXEC_ERR"
        fi
        exit $SSH_EXEC_RC
    fi
}

VMID=`echo ${deploy_id}|cut -d"-" -f2`
NAME="ONE_${VMID}"
vdctool="sudo $vdc/vdc-tool -n ${NAME} "

execute ${dest_host} "$vdctool --stop"    "Failed to stop cache on failed target"
execute ${dest_host} "$vdctool --delete"  "Failed to remove cache from failed target"

exit 0
