#!/bin/bash
# -------------------------------------------------------------------------- #
# Copyright 2013, Gareth Bult <gareth@linux.co.uk>                           #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #
SRC_HOST=$1
DST_HOST=$2
DIR_HOST=$3
VMID=$4
DSID=$5
TEMP=$6

ROOT=$(dirname $(dirname $(dirname $0)))
source ${ROOT}/hooks/vdc/common.sh

CACHE_SIZE="none"
CACHE_LVM="none"
DS_NAME="none"

tool="${ROOT}/hooks/vdc/tool.py"
conf="${ROOT}/hooks/vdc/mkconfig.py"
gids="${ROOT}/hooks/vdc/get_image_ids.py"
vdc="${ROOT}/../vdc-nebula/remotes/binaries"

vdc_log "PostMigrate with NAME=${NAME}"
eval `${gids} $VMID`

#vdctool="sudo $vdc/vdc-tool -n ${NAME} "
#vdcstore="sudo $vdc/vdc-store -n ${NAME} "

vdctool="sudo $vdc/vdc-tool -n ${CACHE} "
vdcstore="sudo $vdc/vdc-store -n ${CACHE} "


while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <($XPATH  	/VM/TEMPLATE/DISK/DATASTORE_ID)

DSID="${XPATH_ELEMENTS[0]}"

vdc_log "${tool} ln $VMID $DSID $DST_HOST"
vdc_log "`${tool} ln $VMID $DSID $DST_HOST`"
eval `${tool} ln $VMID $DSID $SRC_HOST`

CACHE_PATH="/dev/${CACHE_LVM}"

execute ${SRC_HOST} "${vdctool} --stop" "Failed to stop source cache"
execute ${SRC_HOST} "sudo lvremove -f ${CACHE_PATH}/${CACHE}" "Error removing Cache LVM"
#execute ${SRC_HOST} "sudo lvremove -f ${CACHE_PATH}/${NAME}" "Error removing Cache LVM"
exit 0
