#!/bin/bash
# -------------------------------------------------------------------------- #
# Copyright 2013, Gareth Bult <gareth@linux.co.uk>                           #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #
ROOT=$(dirname $(dirname $(dirname $0)))
source ${ROOT}/hooks/vdc/common.sh

ID=$2
vdc_log "Running CLONE with ID=$ID"

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <($XPATH     /DS_DRIVER_ACTION_DATA/DATASTORE/BASE_PATH \
                    /DS_DRIVER_ACTION_DATA/IMAGE/PATH\
                    /DS_DRIVER_ACTION_DATA/DATASTORE/NAME)

BASE_PATH="${XPATH_ELEMENTS[0]}"
SRC="${XPATH_ELEMENTS[1]}"
DST_HOST="${XPATH_ELEMENTS[2]:-$HOST}"

set_up_datastore "$BASE_PATH" "$RESTRICTED_DIRS" "$SAFE_DIRS"
DST=`generate_image_path`
execute $DST_HOST "sudo chown -R oneadmin:oneadmin $SRC"
execute $DST_HOST "cp -rf $SRC $DST" "Error copying $SRC to $DST"
echo "$DST"
exit 0
