#!/bin/bash
# -------------------------------------------------------------------------- #
# Copyright 2013, Gareth Bult <gareth@linux.co.uk>                           #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #
ROOT=$(dirname $(dirname $(dirname $0)))
source ${ROOT}/hooks/vdc/common.sh

conf="${ROOT}/hooks/vdc/mkconfig.py"

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <($XPATH     /DS_DRIVER_ACTION_DATA/IMAGE/SOURCE \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/BASE_PATH \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/NAME)

SRC="${XPATH_ELEMENTS[0]}"
BASE_PATH="${XPATH_ELEMENTS[1]}"
DST_HOST="${XPATH_ELEMENTS[2]}"

BASENAME_SRC=`basename "${SRC##$BASE_PATH}"`

if [ `dirname "$SRC"` = "$BASE_PATH" -a -n "$BASENAME_SRC" ]
then
    log "Removing $SRC from the image repository"
    execute $DST_HOST "rm -rf $SRC" "Error deleting $SRC"
else
    vdc_log "* Error: unable to mark $SRC for deletion"
    exit 1
fi
#execute ${DST_HOST} "sudo ${conf}" "Error Updating VDC Server Config"
exit 0
